# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  logger:
    level: "all"
    stdout: true
    path: "./logs/sql"
  default:
    link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test?loc=Local&parseTime=true"
    extra: "charset=utf8mb4&maxIdle=10&maxLifetime=1000000s&maxOpen=100"